/* eslint-disable @next/next/no-sync-scripts */
/* eslint-disable @next/next/no-css-tags */
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  React.useEffect(() => {
    // AUIGrid 칼럼 레이아웃 설정
    var columnLayout = [
      {
        dataField: "id",
        headerText: "ID",
        width: 140,
      },
      {
        dataField: "name",
        headerText: "Name",
        filter: {
          showIcon: true,
        },
        width: 140,
      },
      {
        dataField: "country",
        headerText: "Country",
        filter: {
          showIcon: true,
        },
        width: 150,
      },
      {
        dataField: "product",
        headerText: "Product",
        width: 150,
      },
      {
        dataField: "color",
        headerText: "Color",
        width: 150,
      },
      {
        dataField: "price",
        headerText: "Price",
        dataType: "numeric",
        style: "my-column",
        width: 150,
        editRenderer: {
          type: "InputEditRenderer",
          onlyNumeric: true, // 0~9만 입력가능
          textAlign: "right", // 오른쪽 정렬로 입력되도록 설정
          autoThousandSeparator: true, // 천단위 구분자 삽입 여부
        },
      },
      {
        dataField: "quantity",
        headerText: "Quantity",
        dataType: "numeric",
        style: "my-column",
        width: 140,
        editRenderer: {
          type: "InputEditRenderer",
          onlyNumeric: true, // 0~9만 입력가능
          textAlign: "right", // 오른쪽 정렬로 입력되도록 설정
          autoThousandSeparator: true, // 천단위 구분자 삽입 여부
        },
      },
      {
        dataField: "date",
        headerText: "Date",
      },
    ];

    // 그리드 속성 설정
    var gridPros = {
      editable: true,

      enableFilter: true,

      // 세로 스크롤 없이 그리드 출력. 그리드 높이는 데이터에 따라 자동 결정됩니다.
      autoGridHeight: true,
    };

    // 실제로 #grid_wrap 에 그리드 생성
    let myGridID = AUIGrid.create("#grid_wrap", columnLayout, gridPros);
    // return () => window.removeEventListener('load', myGridID);
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/static/AUIGrid/AUIGrid_style.css" />
        <script src="/static/AUIGrid/AUIGridLicense.js" />
        <script src="/static/AUIGrid/AUIGrid.js" />
      </Head>

      <div id="grid_wrap"></div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
